apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-tunnel
  template:
    metadata:
      labels:
        app: service-tunnel
    spec:
      initContainers:
      - name: service-tunnel
        image: registry.nordix.org/cloud-native/service-tunnel:latest
        securityContext:
          privileged: true
        env:
        - name: TUNNEL_PEER
          value: "__TUNNEL_PEER__"
        - name: TUNNEL_IPV4
          value: "10.30.30.1/30"
        - name: TUNNEL_IPV6
          value: "fd00:3030::1/126"
      containers:
      - name: alpine
        image: docker.io/library/alpine:3.17.0
        command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: service-tunnel
spec:
  selector:
    app: service-tunnel
  externalTrafficPolicy: Local
  publishNotReadyAddresses: true
  ports:
  - port: 5533
    name: vxlan
    protocol: UDP
  type: LoadBalancer
